version: '3'
services:
  app:
    build:
      context: .
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/logs:/var/log/nginx
    depends_on:
      - db

  webserver:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/html:ro
      - ./docker/nginx/log:/var/log/nginx
    depends_on:
      - app

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
